### ISSUE TITLE
Add more facings and control over image generation in image rotation (every 45 deg. instead of 90).

### ISSUE THREAD

**Issue by bgri** [rubenwe/StlVault#10]
Depending on the object, more facings in the image rotation would give a better understanding of the object. Could be user-selectable (radio button for 20, 45, 90 deg.) also by axis (don't care about Z, just uncheck it before import).

**Comment by rubenwe** [comment]
Fixed in v0.4.1 and up. You can now press ALT when clicking the buttons or ratating via CTRL+ArrowKey to get a smaller amount of rotation.

**Comment by bgri** [comment]
Great! Thanks for taking the suggestion :)
