### ISSUE TITLE
3D View Ignores UI Scaling

### ISSUE THREAD

**Issue by TheCSpider** [rubenwe/StlVault#24]
**What I was doing:**
Adjusted the UI scaling to 50%, then viewed a model in "Open in 3D View"

**Actual Behavior:**
The side panel with "Back" appears to be at the standard 100% UI scale and doesn't change when I either up or down the scaling.

**Expected Behavior:**
That either UI Scaling applies globally or that multiple options are provided to scale different parts of the UI.

**Comment by rubenwe** [comment]
Yep, that's a bug. Thanks for reporting.
