### ISSUE TITLE
Add an "About" tab/box/pop-up

### ISSUE THREAD

**Issue by TheCSpider** [rubenwe/StlVault#29]
Add an About tab/box/pop-up that references back to the webpage (http://stlvault.com/), Facebook, and/or GitHub.

Given the open source nature it may get legs and that would make it easier for folks to find help/latest versions.

**Comment by rubenwe** [comment]
I'll update the user feedback dialog for the next version.
You'll also get (ignorable) popups for new versions.

Thansk for the suggestion!
