### ISSUE TITLE
If you add the same directory multiple times, deletion acts strange

### ISSUE THREAD

**Issue by trek-e** [rubenwe/StlVault#30]
I re-added a directory because I thought I hadn't added it.

There were two behaviors:

One, it re-added it.   Would think maybe should point out it's already there, but that's not a big deal.

What was weird was when there was two, when I deleted the 'new' one, it nuked the contents of the other one too, but didn't remove that.  So now i have an empty folder.  Not a big deal mind you, but probably not the way you want it to behave.

**Comment by rubenwe** [comment]
Thanks for reporting!
